{
  config,
  inputs,
  lib,
  pkgs,
  ...
}:

let
  inherit (config.sops) secrets;

  # `inputs.tonic` is the tonic flake (added in the homelab repo's
  # flake.nix). Both derivations resolve to per-host nixpkgs at the
  # consumer's system — workstation is the only host that activates
  # tonic today, but the lan-route + module shape are host-agnostic.
  backendPkg = inputs.tonic.packages.${pkgs.system}.backend;
  pwaPkg = inputs.tonic.packages.${pkgs.system}.pwa;

  # 909x band is the personal-app range (filmder=9092, heim=9094, hermes=9119).
  # 3000 — tonic's natural default — clashes with gatus's `ops` route.
  servePort = 9095;
in
lib.mkMerge [
  {
    nori.services.tonic.tags = [
      "personal-app"
      "stateful"
    ];

    /*
      Operator-only PWA — Spotify URL → Qobuz FLAC → Opus 128k pipeline.

      `audience = "operator"` ⇒ tailnet trust is the gate; no Authelia.
      No `dashboard = { ... }` entry: this is an operator app (PRD §
      "Auth + access"), reachable via bookmark / direct URL, not the
      family-facing Glance landing page. Matches the family-tier vs
      operator-app convention applied to the *arr stack.
    */
    nori.lanRoutes.tonic = {
      port = servePort;
      runsOn = "workstation";
      audience = "operator";
      monitor = {
        path = "/api/healthz";
      };
    };
  }
  (lib.mkIf config.nori.services.tonic.enabled {
    /*
      tonic — paste-Spotify-URL → workstation downloads via Qobuz →
      transcodes to Opus 128k → Syncthing pushes `music-opus/` to phone.

      Issue #3 wiring: a single supervised systemd unit running the
      Litestar app via uvicorn. Backend serves both the JSON API at
      /api/* and the Vite-built PWA static assets at /. SQLite at
      /var/lib/tonic/queue.sqlite3 (StateDirectory). Source FLACs land
      under ${library}/music; transcoded Opus mirrors the tree under
      ${library}/music-opus.

      ── First-run setup ────────────────────────────────────────────
        1. Encrypt the Qobuz creds into secrets/secrets.yaml:
             tonic-qobuz-credentials: |
               QOBUZ_EMAIL=…
               QOBUZ_PASSWORD=…
        2. `just rebuild` on workstation.
        3. Open https://tonic.${nori.domain} from any tailnet device,
           paste a Spotify track URL, watch the queue advance.
        4. Pair `music-opus/` with phone's Syncthing-Fork (one-time,
           operator-managed in Syncthing's WebUI).

      ── Sleep behaviour ───────────────────────────────────────────
      Workstation sleeps when idle; pi's WOL edge (P19) wakes it on
      first inbound request to tonic.${nori.domain}. Issue #8 verifies
      the wake-on-tonic path explicitly; nothing to wire here.

      ── Why a custom unit, not an upstream NixOS module ───────────
      No upstream module exists. The unit is small (one ExecStart, a
      few env vars) and the runtime contract is owned end-to-end by
      this repo — the backend derivation + the PWA derivation + the
      systemd unit + the lan-route all reference each other through
      `inputs.tonic.packages` rather than via an indirection layer.
    */

    sops.secrets.tonic-qobuz-credentials = {
      # `secrets/secrets.yaml` is the canonical homelab repo's sops file.
      # Operator pre-encrypts an entry with key `tonic-qobuz-credentials`
      # whose body is env-file format: `QOBUZ_EMAIL=…\nQOBUZ_PASSWORD=…`.
      sopsFile = inputs.self + "/secrets/secrets.yaml";
      owner = "tonic";
      mode = "0400";
    };

    /*
      Static `tonic` system user. `media` group membership is the
      load-bearing bit — `${library}/{music,music-opus}` are owned
      `root:media` 02775 by the arr/shared.nix tmpfiles rule, so the
      unit's binds succeed at the systemd level AND the writes succeed
      at the FS level. Without `media`, transcoded Opus files would
      fail with EACCES the first time tonic tried to write under
      `${library}/music-opus/Artist/Album/…`.
    */
    users.users.tonic = {
      isSystemUser = true;
      group = "tonic";
      extraGroups = [ "media" ];
      home = "/var/lib/tonic";
      description = "tonic backend (Spotify URL → Qobuz FLAC → Opus pipeline)";
    };
    users.groups.tonic = { };

    systemd.services.tonic = {
      description = "tonic backend — Spotify URL → Qobuz FLAC → Opus 128k pipeline";
      wantedBy = [ "multi-user.target" ];
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];

      environment = {
        TONIC_PORT = toString servePort;
        TONIC_STATE_DIR = "/var/lib/tonic";
        TONIC_MUSIC_ROOT = "${config.nori.fs.library.path}/music";
        TONIC_OPUS_ROOT = "${config.nori.fs.library.path}/music-opus";
        # PWA path is generated by the flake — single source of truth
        # for "where does the PWA live"; bumping the tonic input
        # automatically bumps this without any homelab-side coordination.
        TONIC_PWA_ROOT = "${pwaPkg}/share/tonic-pwa";
      };

      serviceConfig = {
        Type = "simple";
        User = "tonic";
        Group = "tonic";
        ExecStart = "${lib.getExe backendPkg}";

        EnvironmentFile = secrets.tonic-qobuz-credentials.path;

        # SQLite + WAL files live here. systemd creates the dir 0700
        # owned by User:Group at activation; mode 0750 lets group
        # members read for ad-hoc inspection without exposing to other.
        StateDirectory = "tonic";
        StateDirectoryMode = "0750";

        # OnFailure → notify@tonic.service wired automatically by
        # modules/infra/restart-policy.nix when Restart != "no".
        Restart = "on-failure";
      };
    };

    /*
      Default-deny FS hardening + RW access to the music tier. `binds`
      is RW (matches syncthing.nix's library bind shape) so the worker
      can write source FLACs under `music/` and transcoded Opus files
      under `music-opus/`. The whole library subvol is exposed because
      the directory layout is `${library}/{music,music-opus}` —
      narrower binds would require knowing both subdir paths here AND
      in the worker, a derivation we'd rather avoid.
    */
    nori.harden.tonic.binds = [ config.nori.fs.library.path ];

    /*
      Pattern C2 — sqlite VACUUM INTO dump before restic. The
      queue.sqlite3 is the only irreplaceable state tonic owns:

       - `${library}/music`      irreplaceable per nori.fs's library
                                 entry, covered by the library subvol's
                                 own backup regime — not tonic's job.
       - `${library}/music-opus` transcoded output, re-derives from
                                 `music/` byte-identically via the
                                 SOURCE_BLAKE3 invariant (PRD §
                                 Idempotency). Intentionally excluded
                                 from backups: re-derivable from music/.

      VACUUM INTO + busy_timeout matches the canonical Pattern C2 shape
      in navidrome.nix / open-webui.nix / vaultwarden.nix. flock
      serializes against concurrent target prep (same race the
      navidrome module documents).

      Static `tonic` user (NOT DynamicUser), so /var/lib/tonic is a
      real directory — no DynamicUser symlink-to-/var/lib/private trap.
    */
    nori.backups.tonic = {
      include = [
        "/var/backup/tonic"
      ];
      prepareCommand = ''
        if [ -f /var/lib/tonic/queue.sqlite3 ]; then
          mkdir -p /var/backup/tonic
          (
            ${pkgs.util-linux}/bin/flock -x 9
            rm -f /var/backup/tonic/queue.sqlite3.tmp
            ${pkgs.sqlite}/bin/sqlite3 /var/lib/tonic/queue.sqlite3 \
              "PRAGMA busy_timeout = 30000;" \
              "VACUUM INTO '/var/backup/tonic/queue.sqlite3.tmp';"
            mv /var/backup/tonic/queue.sqlite3.tmp /var/backup/tonic/queue.sqlite3
          ) 9>/var/backup/tonic/.prep.lock
        fi
      '';
      timer = "*-*-* 05:00:00"; # stagger off other Pattern C2 jobs (04:30, 04:45)
    };
  })
]
