---
caddy_tls_mode: "{{ 'internal' if pi_emulation_mode else 'cloudflare' }}"
caddy_builder_image: >-
  docker.io/library/caddy:2.10.2-builder-alpine@sha256:4cff3ae272ea05842adb4546e35961e4947aeea65f80fa1eb62a35b960e84971
caddy_runtime_image: >-
  docker.io/library/caddy:2.10.2-alpine@sha256:4c6e91c6ed0e2fa03efd5b44747b625fec79bc9cd06ac5235a779726618e530d
caddy_cloudflare_plugin: github.com/caddy-dns/cloudflare@v0.2.4
caddy_build_custom_image: "{{ not pi_emulation_mode }}"
caddy_image: >-
  {{ 'localhost/homelab-caddy:2.10.2-cloudflare-0.2.4'
     if caddy_build_custom_image else caddy_runtime_image }}
