{
  config,
  lib,
  inputs,
  ...
}:

{
  # workstation is a server + a desktop. Each `modules/<concern>`
  # import is one role this machine plays; the host is the sum of
  # its concerns plus its physical hardware.
  imports = [
    inputs.disko.nixosModules.disko
    inputs.home-manager.nixosModules.home-manager

    ../../modules/common # base + users + sops + tailscale + lib options
    ../../modules/services # every server module (HTTP, *arr, backup, …)
    ../../modules/desktop # Hyprland + greetd + audio + bars + apps + gaming
    ../../modules/services/hermes.nix # hermes.nori.lan → user dashboard on 127.0.0.1:9119

    ./hardware.nix
    ./disko.nix
    ./disko-media.nix
    ./disko-mp510.nix
  ];

  # home-manager-as-NixOS-module wrapper. Activates the user's home
  # config (./home.nix — pure home-manager module shape) as part of
  # nixos-rebuild. The same shape lives in machines/pi/default.nix;
  # extract a shared snippet at the third instance.
  home-manager = {
    useGlobalPkgs = true; # use system nixpkgs, don't fork a per-user one
    useUserPackages = true; # install user pkgs to /etc/profiles/per-user
    extraSpecialArgs = { inherit inputs; };
    # Move pre-existing files aside instead of failing the activation
    # when home-manager wants to symlink in a managed copy. Bit us once
    # already: Hyprland writes an autogenerated ~/.config/hypr/
    # hyprland.conf on first launch if no config exists; if the user
    # logs in before home-manager has activated, the file lands first
    # and HM refuses to clobber. Backed-up file lands at <path>.hm-backup.
    backupFileExtension = "hm-backup";
    users.nori.imports = [ ./home.nix ];
  };

  # networking.hostName injected from the registry key in flake.nix.
  networking.useDHCP = lib.mkDefault true;

  # Add the operator user to the `media` group so shell access + any
  # service running as `nori` (Syncthing's binds, e.g.) can write to
  # /mnt/media/{downloads,library} which are owned root:media 02775
  # by arr/shared.nix tmpfiles. The group itself is defined in
  # arr/shared.nix — workstation-only, hence the workstation-host-
  # scope here rather than common/users.nix (which Pi also reads).
  users.users.nori.extraGroups = [ "media" ];

  # Service-placement registry (aurora migration P3). Reproduces today's
  # workstation activation set exactly — each modules/services/*.nix
  # that wraps itself in `mkIf config.nori.services.<name>.enabled`
  # gets explicitly enabled here. Net effect under P2 wrap + this
  # opt-in is zero behavior change. Future moves between hosts:
  # flip `enable` on the destination, unset here.
  #
  # Workstation is the workhorse — it currently runs everything in
  # the modules/services/ bundle (modules/services/default.nix). The
  # P12 cutover moves the family-tier services to aurora by flipping
  # `enable` on aurora and unsetting here.
  nori.services = {
    # arr stack + qBit (media-server)
    bazarr.enable = true;
    jellyseerr.enable = true;
    lidarr.enable = true;
    prowlarr.enable = true;
    qbittorrent.enable = true;
    radarr.enable = true;
    recyclarr.enable = true;
    sonarr.enable = true;
    # Family-tier + network appliance + media-reader
    authelia.enable = true;
    blocky.enable = true;
    caddy.enable = true;
    calibre-web.enable = true;
    filmder.enable = false;
    glance.enable = false;
    heim.enable = false;
    immich.enable = true;
    jellyfin.enable = true;
    komga.enable = true;
    miniflux.enable = false;
    navidrome.enable = true;
    open-webui.enable = true;
    radicale.enable = false;
    samba.enable = true;
    stremio.enable = true;
    syncthing.enable = true;
    vaultwarden.enable = false;
    # GPU-bound
    ollama.enable = true;
    # Observability + alerting
    beszel-agent.enable = true;
    disk-alert.enable = true;
    gatus.enable = true;
    grafana.enable = false;
    node-exporter.enable = true;
    nvidia-gpu-exporter.enable = true;
    ntfy-notify.enable = true;
  };

  # Defensive cap on user@1000.service. Calibrated against the
  # 2026-06-08 global-OOM event: a leak inside the user session climbed
  # to 26.2 GiB RSS + 21.5 GiB swap peak in 3h, exhausted total memory
  # (32 GiB RAM + 16 GiB zram + 8 GiB disk swap), and the kernel OOM
  # killer fired with CONSTRAINT_NONE — killing lua-language-server
  # inside the Hyprland session and cascading user@1000 to deactivate,
  # taking down the entire desktop.
  #
  # MemoryHigh = soft cap, throttles via swap pressure when reached.
  # MemoryMax  = hard cap, OOM-kills inside the unit instead of system-
  #              wide. With the cap, a runaway desktop kills itself and
  #              system services (sshd, caddy, blocky, tailscaled) stay
  #              alive — recoverable from a TTY or remote SSH.
  #
  # Numbers leave ≥4 GiB physical + 8 GiB swap headroom for kernel,
  # system slice, and a brief grace for terminating processes. Track
  # the actual session footprint in process-exporter (ROADMAP #45) and
  # tighten if normal heavy use stays well under.
  systemd.services."user@".serviceConfig = {
    MemoryHigh = "24G";
    MemoryMax = "28G";
  };

  # Station-side Gatus probes for non-HTTP services. HTTP services
  # behind Caddy are auto-probed via nori.lanRoutes.<n>.monitor.
  #
  # Mutual observability: station probes Pi's Blocky + SSH via tailnet
  # IP; pi has matching probes for station (machines/pi/default.nix).
  # Each host's Gatus alerts via ntfy.sh directly (no local-ntfy
  # dependency), so one host's outage gets caught by the other.
  nori.gatusProbes = {
    blocky-dns.url = "tcp://127.0.0.1:53";
    samba-smb.url = "tcp://127.0.0.1:445";
    pi-blocky-dns.url = "tcp://${config.nori.hosts.pi.tailnetIp}:53";
    pi-ssh.url = "tcp://${config.nori.hosts.pi.tailnetIp}:22";
  };
}
