{
  config,
  lib,
  inputs,
  ...
}:

{
  # workstation is a server + a desktop. Each `modules/<concern>`
  # import is one role this machine plays; the host is the sum of
  # its concerns plus its physical hardware.
  imports = [
    inputs.disko.nixosModules.disko
    inputs.home-manager.nixosModules.home-manager

    ../../modules/common # base + users + sops + tailscale + lib options
    ../../modules/server # every server module (HTTP, *arr, backup, …)
    ../../modules/desktop # Hyprland + greetd + audio + bars + apps + gaming
    ../../modules/hermes/route.nix # hermes.nori.lan → user dashboard on 127.0.0.1:9119

    ./hardware.nix
    ./disko.nix
    ./disko-media.nix
    ./disko-onetouch.nix
    ./windows-mount.nix
  ];

  # home-manager-as-NixOS-module wrapper. Activates the user's home
  # config (./home.nix — pure home-manager module shape) as part of
  # nixos-rebuild. The same shape lives in machines/pi/default.nix;
  # extract a shared snippet at the third instance.
  home-manager = {
    useGlobalPkgs = true; # use system nixpkgs, don't fork a per-user one
    useUserPackages = true; # install user pkgs to /etc/profiles/per-user
    extraSpecialArgs = { inherit inputs; };
    # Move pre-existing files aside instead of failing the activation
    # when home-manager wants to symlink in a managed copy. Bit us once
    # already: Hyprland writes an autogenerated ~/.config/hypr/
    # hyprland.conf on first launch if no config exists; if the user
    # logs in before home-manager has activated, the file lands first
    # and HM refuses to clobber. Backed-up file lands at <path>.hm-backup.
    backupFileExtension = "hm-backup";
    users.nori.imports = [ ./home.nix ];
  };

  # networking.hostName injected from the registry key in flake.nix.
  networking.useDHCP = lib.mkDefault true;

  # Add the operator user to the `media` group so shell access + any
  # service running as `nori` (Syncthing's binds, e.g.) can write to
  # /mnt/media/{downloads,library} which are owned root:media 02775
  # by arr/shared.nix tmpfiles. The group itself is defined in
  # arr/shared.nix — workstation-only, hence the workstation-host-
  # scope here rather than common/users.nix (which Pi also reads).
  users.users.nori.extraGroups = [ "media" ];

  # Station-side Gatus probes for non-HTTP services. HTTP services
  # behind Caddy are auto-probed via nori.lanRoutes.<n>.monitor.
  #
  # Mutual observability: station probes Pi's Blocky + SSH via tailnet
  # IP; pi has matching probes for station (machines/pi/default.nix).
  # Each host's Gatus alerts via ntfy.sh directly (no local-ntfy
  # dependency), so one host's outage gets caught by the other.
  nori.gatusProbes = {
    blocky-dns.url = "tcp://127.0.0.1:53";
    samba-smb.url = "tcp://127.0.0.1:445";
    pi-blocky-dns.url = "tcp://${config.nori.hosts.pi.tailnetIp}:53";
    pi-ssh.url = "tcp://${config.nori.hosts.pi.tailnetIp}:22";
  };
}
