{
  config,
  lib,
  inputs,
  ...
}:

{
  # workstation is a server + a desktop. Each `modules/<concern>`
  # import is one role this machine plays; the host is the sum of
  # its concerns plus its physical hardware.
  imports = [
    inputs.disko.nixosModules.disko
    inputs.home-manager.nixosModules.home-manager

    ../../modules/common # base + users + sops + tailscale + lib options
    ../../modules/server # every server module (HTTP, *arr, backup, …)
    ../../modules/desktop # Hyprland + greetd + audio + bars + apps + gaming

    ./hardware.nix
    ./disko.nix
    ./disko-media.nix
    ./disko-onetouch.nix
    ./windows-mount.nix
  ];

  # home-manager-as-NixOS-module wrapper. Activates the user's home
  # config (./home.nix — pure home-manager module shape) as part of
  # nixos-rebuild. The same shape lives in machines/pi/default.nix;
  # extract a shared snippet at the third instance.
  home-manager = {
    useGlobalPkgs = true; # use system nixpkgs, don't fork a per-user one
    useUserPackages = true; # install user pkgs to /etc/profiles/per-user
    extraSpecialArgs = { inherit inputs; };
    # Move pre-existing files aside instead of failing the activation
    # when home-manager wants to symlink in a managed copy. Bit us once
    # already: Hyprland writes an autogenerated ~/.config/hypr/
    # hyprland.conf on first launch if no config exists; if the user
    # logs in before home-manager has activated, the file lands first
    # and HM refuses to clobber. Backed-up file lands at <path>.hm-backup.
    backupFileExtension = "hm-backup";
    users.nori.imports = [ ./home.nix ];
  };

  # networking.hostName injected from the registry key in flake.nix.
  networking.useDHCP = lib.mkDefault true;

  # Station-side Gatus probes for non-HTTP services (these don't fit
  # the lan-route auto-gen pattern). HTTP services behind Caddy are
  # auto-probed via nori.lanRoutes.<n>.monitor — see
  # modules/effects/lan-route.nix.
  #
  # Mutual observability: station probes Pi's Blocky + SSH via
  # tailnet IP. Pi has matching probes for station — see
  # hosts/pi/default.nix. Each host's Gatus alerts via ntfy.sh
  # directly (no local-ntfy dependency), so when one host wedges
  # the other catches it.
  services.gatus.settings.endpoints = [
    {
      name = "blocky-dns";
      url = "tcp://127.0.0.1:53";
      interval = "60s";
      conditions = [ "[CONNECTED] == true" ];
      alerts = [
        {
          type = "ntfy";
          failure-threshold = 3;
          send-on-resolved = true;
        }
      ];
    }
    {
      name = "samba-smb";
      url = "tcp://127.0.0.1:445";
      interval = "60s";
      conditions = [ "[CONNECTED] == true" ];
      alerts = [
        {
          type = "ntfy";
          failure-threshold = 3;
          send-on-resolved = true;
        }
      ];
    }
    {
      # pi's Blocky on tailnet IP — catches Pi outage even if
      # Pi's Gatus is down (same incident pattern in reverse). Pi's
      # tailnet IP comes from the nori.hosts registry; topology
      # changes are a one-line edit in modules/common/topology.nix.
      name = "pi-blocky-dns";
      url = "tcp://${config.nori.hosts.pi.tailnetIp}:53";
      interval = "60s";
      conditions = [ "[CONNECTED] == true" ];
      alerts = [
        {
          type = "ntfy";
          failure-threshold = 3;
          send-on-resolved = true;
        }
      ];
    }
    {
      # pi's SSH — full host-down detection (sshd dead = host
      # effectively gone from operator's perspective).
      name = "pi-ssh";
      url = "tcp://${config.nori.hosts.pi.tailnetIp}:22";
      interval = "60s";
      conditions = [ "[CONNECTED] == true" ];
      alerts = [
        {
          type = "ntfy";
          failure-threshold = 3;
          send-on-resolved = true;
        }
      ];
    }
  ];
}
