/**
  e2e Phases 1-6 — pi-alone smoke nixosTest.

  Boots a stripped-down pi-like NixOS config in a QEMU VM and verifies
  the homelab's entry-plane services reach active state. Per-phase
  scope:

   - Phase 1: framework smoke (bare nixpkgs blocky)
   - Phase 2: homelab blocky + lanRoutes → customDNS pipeline
   - Phase 3: + gatus.timer + heartbeat.timer (timer-driven
     activation pattern)
   - Phase 4: + caddy.service with internal-CA mode
   - Phase 6: + authelia-main.service with REAL sops + real
     argon2id user hash + real RSA-PSS issuer key. Supersedes
     the deferred Phase 5 attempt — the lesson was that authelia
     can't be tested with option-schema stubs (it parses every
     secret at startup), so the test secrets are now real-shape
     generated by scripts/regen-test-secrets.sh.

  All secrets resolve through the REAL sops-nix module against
  tests/secrets/test.yaml (encrypted to the test-only age recipient
  at tests/keys/test-age.txt). No fixtures, no stubs in the data
  plane — composition itself is what gets tested.

  Per docs/reference/testing-methodology.md, this is LAYER 2 of the
  three-layer pyramid — pair with layer-1 eval tests at tests/eval/
  for sub-second feedback during inner-loop iteration. Use
  `just e2e-shell e2e-pi-smoke` to open the interactive driver +
  iterate on testScript fragments without rebuilding.

  Invoked via nix build .#checks.<system>.e2e-pi-smoke.
*/
{
  pkgs,
  lib,
  inputs,
  ...
}:

pkgs.testers.runNixOSTest {
  name = "e2e-pi-smoke";

  # Same `inputs` plumbing real nixosConfigurations get at flake-
  # build time. Homelab modules consume `inputs` for impermanence /
  # nixos-hardware refs even when those features aren't active.
  node.specialArgs = { inherit inputs; };

  nodes.pi =
    { config, lib, ... }:
    {
      imports = [
        # Real sops-nix — decrypts tests/secrets/test.yaml at activation
        # using tests/keys/test-age.txt. No stub: the test exercises the
        # exact decrypt → plant → consume path production uses, just
        # against committed test data.
        inputs.sops-nix.nixosModules.sops

        # Infra schemas the homelab blocky module reads through.
        ../modules/infra/hosts.nix
        ../modules/infra/placement.nix
        ../modules/infra/capabilities
        ../modules/infra/storage # nori.fs (consumed by backup/btrbk)
        ../modules/infra/backup
        ../modules/infra/networking

        # Observability — selected submodules. Skipping the full
        # bundle import to avoid pulling in vector (needs a
        # VictoriaLogs server) + beszel agent (would try to register
        # with a hub) + node-exporter / nvidia-gpu-exporter (not
        # needed for smoke). Phase 4 picks up the fuller observability
        # set.
        ../modules/infra/observability/gatus.nix
        ../modules/infra/observability/heartbeat.nix

        # Phase 6 — authelia OIDC. Imports the real module path
        # production uses; secrets resolve via the test sops file
        # (RSA issuer key + argon2id user hash were generated by
        # scripts/regen-test-secrets.sh).
        ../modules/infra/access
      ];

      # Real sops, test recipient. sops-nix refuses store-path
      # keyFiles (the key has to be readable at runtime), so plant the
      # test key at /etc/sops-test-age.txt via environment.etc and
      # point sops at THAT runtime path. The secrets file IS allowed
      # to be a Nix path — sops-nix copies it into the store at eval
      # time. See scripts/regen-test-secrets.sh for generation.
      environment.etc."sops-test-age.txt".source = ./keys/test-age.txt;
      sops.age.keyFile = "/etc/sops-test-age.txt";
      sops.age.sshKeyPaths = lib.mkForce [ ];
      sops.defaultSopsFile = ./secrets/test.yaml;

      # Synthetic identity — provides nori.hosts registry entries
      # that placement assertions consult.
      nori.hosts = {
        pi = {
          tailnetIp = "100.0.0.1";
          lanIp = "10.0.0.10";
          role = "appliance";
          roleOneLiner = "";
          codename = "test-pi";
          hardware = "test-qemu";
          primaryJob = "Phase 2 smoke";
        };
        workstation = {
          tailnetIp = "100.0.0.2";
          lanIp = "10.0.0.20";
          role = "workhorse";
          roleOneLiner = "test workhorse";
          codename = "test-station";
          hardware = "test-qemu";
          primaryJob = "Phase 2 smoke";
        };
      };

      networking.hostName = "pi";
      nori.domain = "test.lan";
      nori.lanIp = lib.mkForce "10.0.0.20";

      # Test routes — exercise the lanRoutes → blocky.customDNS
      # auto-generation pipeline. Two routes so we can verify both
      # resolve identically (to nori.lanIp).
      nori.lanRoutes.smoke = {
        port = 9999;
        runsOn = "workstation";
      };
      nori.lanRoutes.another = {
        port = 8888;
        runsOn = "workstation";
      };
      # Phase 6 — exercise the OIDC client codepath. Authelia's config
      # validator rejects an empty `identity_providers.oidc.clients`
      # list, so the test declares one route with .oidc set. The
      # networking module auto-generates the two sops secrets
      # (oidc-testapp-client-secret + ...-hash); their values are in
      # tests/secrets/test.yaml.
      nori.lanRoutes.testapp = {
        port = 7777;
        runsOn = "workstation";
        oidc = {
          clientName = "Test App";
          redirectPath = "/oauth/callback";
        };
      };

      nori.services.blocky.enable = true;
      nori.services.gatus.enable = true;
      nori.services.heartbeat.enable = true;
      nori.services.caddy.enable = true;
      nori.services.authelia.enable = true;
      nori.blocky.role = "self-hosted";

      # Stub backup target — required because caddy declares
      # `nori.backups.caddy.include = [...]` and the backup module
      # asserts that any active paths-backup needs ≥1 target. Test
      # doesn't actually run restic (would need real repo + key);
      # the target just satisfies the assertion.
      nori.backupTargets.test-stub = {
        # Use a remote-shaped URL to satisfy the appliance-host
        # assertion (pi role=appliance can't have LOCAL restic
        # targets — anti-write storage posture). Test never actually
        # runs restic; the URL is never dialed.
        repository = "sftp:stub@stub.test:/stub";
        description = "test stub; never actually used";
      };
      # backup/default.nix reads config.sops.secrets.restic-password
      # at eval. modules/infra/backup/restic.nix declares it but only
      # on workstation; the test config has hostName="pi", so declare
      # it here. The value already lives in tests/secrets/test.yaml.
      sops.secrets.restic-password = { };

      # Caddy test overrides — skip ACME, skip cloudflare plugin.
      services.caddy.package = lib.mkForce pkgs.caddy;
      services.caddy.globalConfig = lib.mkForce ''
        # `local_certs` makes Caddy issue self-signed certs from its
        # internal CA for ALL sites — no external ACME contact, no
        # cloudflare token required. Standard pattern for test envs.
        local_certs
      '';

      # caddy.nix hardcodes sopsFile = ../../secrets/apps.yaml for the
      # cloudflare-acme-token. Test secrets live elsewhere — point at
      # tests/secrets/test.yaml. The token isn't actually used by the
      # local_certs path; it just needs to decrypt cleanly so the
      # template + secret activation steps complete.
      sops.secrets.cloudflare-acme-token.sopsFile = lib.mkForce ./secrets/test.yaml;

      # Test framework's nixpkgs.config differs from base.nix's;
      # force ours to match the test framework to avoid the
      # allowUnfree conflict.
      nixpkgs.config = lib.mkForce {
        allowAliases = true;
        allowBroken = false;
        allowUnfree = false;
      };

      # Smaller closure for faster test boot.
      documentation.enable = lib.mkForce false;

      # `dig` for the DNS-resolution assertions in testScript.
      environment.systemPackages = [ pkgs.bind.dnsutils ];
    };

  testScript = ''
    start_all()
    pi.wait_for_unit("multi-user.target")

    with subtest("blocky.service reaches active state"):
        pi.wait_for_unit("blocky.service")
        pi.wait_for_open_port(53)

    with subtest("lanRoutes → blocky customDNS auto-generation works"):
        # smoke.test.lan and another.test.lan are both declared in
        # nori.lanRoutes; the networking module's customDNS generator
        # should map each to nori.lanIp (10.0.0.20) automatically.
        smoke = pi.succeed("dig +short +time=2 +tries=1 smoke.test.lan @127.0.0.1")
        assert "10.0.0.20" in smoke, f"smoke.test.lan: expected 10.0.0.20, got: {smoke!r}"

        another = pi.succeed("dig +short +time=2 +tries=1 another.test.lan @127.0.0.1")
        assert "10.0.0.20" in another, f"another.test.lan: expected 10.0.0.20, got: {another!r}"

    with subtest("gatus.timer activates"):
        # gatus.service has wantedBy=[] in the homelab module — it's
        # fired by gatus.timer at OnBootSec=60s instead (so cross-host
        # rebuilds don't trigger probe-flapping). Wait for the timer
        # to be active; the service itself starts on the timer's
        # schedule.
        pi.wait_for_unit("gatus.timer")

    with subtest("heartbeat.timer activates"):
        # heartbeat.service is a oneshot — the timer wants to fire it
        # every 60s. We don't care if the curl succeeds (the URL is
        # a stub comment, not a real hc.io endpoint); we DO care that
        # the timer activates without systemd refusing to load it.
        pi.wait_for_unit("heartbeat.timer")

    with subtest("caddy.service starts + binds :443"):
        # caddy uses local_certs (internal CA) — no real ACME contact.
        # Validates: caddy module evals, the auto-generated vhost
        # config (from nori.lanRoutes) is syntactically valid, caddy
        # binds to :443. Doesn't try to proxy requests through to
        # synthetic backends — upstreams aren't reachable in this
        # single-node test.
        pi.wait_for_unit("caddy.service")
        pi.wait_for_open_port(443)

    with subtest("authelia-main.service starts + binds :9091"):
        # The real load-bearing Phase 6 check. Authelia parses every
        # decrypted secret at startup — argon2id user hash, RSA-PSS
        # issuer key, storage-encryption-key length, jwt/session/
        # hmac secrets. If any one is malformed, authelia-main exits
        # non-zero within seconds. Reaching active + binding 9091
        # proves the entire sops → file → authelia parse pipeline is
        # composed correctly.
        pi.wait_for_unit("authelia-main.service")
        pi.wait_for_open_port(9091)

        # Health probe — authelia exposes /api/health unauthenticated.
        # `ok` confirms it's not just listening but actually serving.
        health = pi.succeed("curl -fsS http://127.0.0.1:9091/api/health")
        assert "OK" in health or "ok" in health, f"unhealthy: {health!r}"
  '';
}
