/**
  e2e Phases 1-7 — pi-alone smoke nixosTest.

  Boots a stripped-down pi-like NixOS config in a QEMU VM and verifies
  the homelab's entry-plane services reach active state. Per-phase
  scope:

   - Phase 1: framework smoke (bare nixpkgs blocky)
   - Phase 2: homelab blocky + lanRoutes → customDNS pipeline
   - Phase 3: + gatus.timer + heartbeat.timer (timer-driven
     activation pattern)
   - Phase 4: + caddy.service with internal-CA mode
   - Phase 6: + authelia-main.service with REAL sops + real
     argon2id user hash + real RSA-PSS issuer key. Supersedes
     the deferred Phase 5 attempt — the lesson was that authelia
     can't be tested with option-schema stubs (it parses every
     secret at startup), so the test secrets are now real-shape
     generated by scripts/regen-test-secrets.sh. Also adds the
     OIDC discovery + first-factor login flow via curl through
     caddy, proving the entire auth path composes.
   - Phase 7: + OnFailure → notify@ → ntfy POST pipeline. Stub
     receiver in-VM captures the POST so the test can assert the
     real systemd unit fires, the script reads the sops channel,
     and the alert URL + body shape are correct.

  All secrets resolve through the REAL sops-nix module against
  tests/secrets/test.yaml (encrypted to the test-only age recipient
  at tests/keys/test-age.txt). No fixtures, no stubs in the data
  plane — composition itself is what gets tested.

  Per docs/reference/testing-methodology.md, this is LAYER 2 of the
  three-layer pyramid — pair with layer-1 eval tests at tests/eval/
  for sub-second feedback during inner-loop iteration. Use
  `just e2e-shell e2e-pi-smoke` to open the interactive driver +
  iterate on testScript fragments without rebuilding.

  Invoked via nix build .#checks.<system>.e2e-pi-smoke.
*/
{
  pkgs,
  lib,
  inputs,
  ...
}:

pkgs.testers.runNixOSTest {
  name = "e2e-pi-smoke";

  # Same `inputs` plumbing real nixosConfigurations get at flake-
  # build time. Homelab modules consume `inputs` for impermanence /
  # nixos-hardware refs even when those features aren't active.
  node.specialArgs = { inherit inputs; };

  nodes.pi =
    { config, lib, ... }:
    {
      imports = [
        # Real sops-nix — decrypts tests/secrets/test.yaml at activation
        # using tests/keys/test-age.txt. No stub: the test exercises the
        # exact decrypt → plant → consume path production uses, just
        # against committed test data.
        inputs.sops-nix.nixosModules.sops

        # Infra schemas the homelab blocky module reads through.
        ../modules/infra/hosts.nix
        ../modules/infra/placement.nix
        ../modules/infra/capabilities
        ../modules/infra/storage # nori.fs (consumed by backup/btrbk)
        ../modules/infra/backup
        ../modules/infra/networking

        # Observability — selected submodules. Skipping the full
        # bundle import to avoid pulling in vector (needs a
        # VictoriaLogs server) + beszel agent (would try to register
        # with a hub) + node-exporter / nvidia-gpu-exporter (not
        # needed for smoke). Phase 4 picks up the fuller observability
        # set.
        ../modules/infra/observability/gatus.nix
        ../modules/infra/observability/heartbeat.nix
        # Phase 7 — OnFailure → notify@ → ntfy POST. Module declares
        # the systemd template + the channel sops secret; the test
        # overrides nori.observability.ntfyNotify.{baseUrl,
        # recoveryWindowSeconds} to point at the local stub.
        ../modules/infra/observability/ntfy/notify.nix

        # Phase 6 — authelia OIDC. Imports the real module path
        # production uses; secrets resolve via the test sops file
        # (RSA issuer key + argon2id user hash were generated by
        # scripts/regen-test-secrets.sh).
        ../modules/infra/access
      ];

      # Real sops, test recipient. sops-nix refuses store-path
      # keyFiles (the key has to be readable at runtime), so plant the
      # test key at /etc/sops-test-age.txt via environment.etc and
      # point sops at THAT runtime path. The secrets file IS allowed
      # to be a Nix path — sops-nix copies it into the store at eval
      # time. See scripts/regen-test-secrets.sh for generation.
      environment.etc."sops-test-age.txt".source = ./keys/test-age.txt;
      sops.age.keyFile = "/etc/sops-test-age.txt";
      sops.age.sshKeyPaths = lib.mkForce [ ];
      sops.defaultSopsFile = ./secrets/test.yaml;

      # Synthetic identity — provides nori.hosts registry entries
      # that placement assertions consult.
      nori.hosts = {
        pi = {
          tailnetIp = "100.0.0.1";
          lanIp = "10.0.0.10";
          role = "appliance";
          roleOneLiner = "";
          codename = "test-pi";
          hardware = "test-qemu";
          primaryJob = "Phase 2 smoke";
        };
        workstation = {
          tailnetIp = "100.0.0.2";
          lanIp = "10.0.0.20";
          role = "workhorse";
          roleOneLiner = "test workhorse";
          codename = "test-station";
          hardware = "test-qemu";
          primaryJob = "Phase 2 smoke";
        };
      };

      networking.hostName = "pi";
      nori.domain = "test.lan";
      nori.lanIp = lib.mkForce "10.0.0.20";

      # Test routes — exercise the lanRoutes → blocky.customDNS
      # auto-generation pipeline. Two routes so we can verify both
      # resolve identically (to nori.lanIp).
      nori.lanRoutes.smoke = {
        port = 9999;
        runsOn = "workstation";
      };
      nori.lanRoutes.another = {
        port = 8888;
        runsOn = "workstation";
      };
      # Phase 6 — exercise the OIDC client codepath. Authelia's config
      # validator rejects an empty `identity_providers.oidc.clients`
      # list, so the test declares one route with .oidc set. The
      # networking module auto-generates the two sops secrets
      # (oidc-testapp-client-secret + ...-hash); their values are in
      # tests/secrets/test.yaml.
      nori.lanRoutes.testapp = {
        port = 7777;
        runsOn = "workstation";
        oidc = {
          clientName = "Test App";
          redirectPath = "/oauth/callback";
        };
      };

      # forwardAuth-gated route — the OTHER auth pattern (vs OIDC).
      # Caddy asks authelia's /api/verify whether the request has a
      # valid session cookie BEFORE forwarding. The backend runs
      # locally (runsOn = "pi") so the test stays single-node.
      nori.lanRoutes.gated = {
        port = 7878;
        runsOn = "pi";
        forwardAuth = {
          # Default exemptPaths = [ "/api/*" ]; we keep that so the
          # gated.test.lan/api/* exemption can be exercised too.
        };
      };

      # Trivial backend behind the gated route. Responds with a
      # deterministic marker so the testScript can confirm a 200
      # carried real backend bytes (not authelia's portal HTML).
      systemd.services.gated-backend = {
        description = "Test backend for the forwardAuth-gated route";
        wantedBy = [ "multi-user.target" ];
        after = [ "network.target" ];
        serviceConfig = {
          ExecStart = "${pkgs.python3}/bin/python3 ${pkgs.writeText "gated-backend.py" ''
            import http.server
            class H(http.server.BaseHTTPRequestHandler):
                def do_GET(self):
                    self.send_response(200)
                    self.send_header("Content-Type", "text/plain")
                    self.end_headers()
                    body = b"gated-backend-ok" if self.path == "/" else b"api-exempt-ok"
                    self.wfile.write(body)
                def log_message(self, *a, **k): pass
            http.server.HTTPServer(("127.0.0.1", 7878), H).serve_forever()
          ''}";
        };
      };

      nori.services.blocky.enable = true;
      nori.services.gatus.enable = true;
      nori.services.heartbeat.enable = true;
      nori.services.caddy.enable = true;
      nori.services.authelia.enable = true;
      nori.services.ntfy-notify.enable = true;
      nori.blocky.role = "self-hosted";

      # Phase 7 — redirect ntfy POSTs to the in-VM stub receiver +
      # shrink the recovery window so the test cycle stays short.
      # Both knobs are real production options with sane defaults;
      # tests override, prod doesn't have to know they exist.
      nori.observability.ntfyNotify = {
        baseUrl = "http://127.0.0.1:9999";
        recoveryWindowSeconds = 3;
      };

      # Stub ntfy receiver — a tiny python HTTP server that writes
      # every POST it gets to /var/lib/test-ntfy/messages. The
      # notify@ pipeline POSTs to baseUrl + "/" + channel; our stub
      # captures the body + headers so the testScript can assert
      # the alert went through with the right shape.
      systemd.services.test-ntfy-receiver = {
        description = "Phase 7 stub — captures ntfy POSTs for the OnFailure test";
        wantedBy = [ "multi-user.target" ];
        after = [ "network.target" ];
        serviceConfig = {
          Type = "simple";
          StateDirectory = "test-ntfy";
          ExecStart = "${pkgs.python3}/bin/python3 ${pkgs.writeText "test-ntfy-receiver.py" ''
            import http.server
            class H(http.server.BaseHTTPRequestHandler):
                def do_POST(self):
                    n = int(self.headers.get("Content-Length", 0))
                    body = self.rfile.read(n).decode("utf-8", errors="replace")
                    with open("/var/lib/test-ntfy/messages", "a") as f:
                        f.write(f"PATH={self.path}\n")
                        for k, v in self.headers.items():
                            f.write(f"HDR {k}: {v}\n")
                        f.write(f"BODY={body}\n---\n")
                    self.send_response(200)
                    self.end_headers()
                    self.wfile.write(b"ok")
                def log_message(self, *a, **k):
                    pass
            http.server.HTTPServer(("127.0.0.1", 9999), H).serve_forever()
          ''}";
        };
      };

      # A unit that fails deterministically — the bait. OnFailure
      # uses the literal instance name (matching the production
      # pattern in modules/infra/backup/verify.nix etc — %n would
      # produce "notify@test-failing-unit.service.service" because
      # systemd appends .service when looking up the template).
      systemd.services.test-failing-unit = {
        description = "Phase 7 — intentionally failing unit; bait for notify@";
        # Don't start automatically — the testScript triggers it.
        serviceConfig = {
          Type = "oneshot";
          ExecStart = "${pkgs.coreutils}/bin/false";
        };
        unitConfig.OnFailure = [ "notify@test-failing-unit.service" ];
      };

      # Stub backup target — required because caddy declares
      # `nori.backups.caddy.include = [...]` and the backup module
      # asserts that any active paths-backup needs ≥1 target. Test
      # doesn't actually run restic (would need real repo + key);
      # the target just satisfies the assertion.
      nori.backupTargets.test-stub = {
        # Use a remote-shaped URL to satisfy the appliance-host
        # assertion (pi role=appliance can't have LOCAL restic
        # targets — anti-write storage posture). Test never actually
        # runs restic; the URL is never dialed.
        repository = "sftp:stub@stub.test:/stub";
        description = "test stub; never actually used";
      };
      # backup/default.nix reads config.sops.secrets.restic-password
      # at eval. modules/infra/backup/restic.nix declares it but only
      # on workstation; the test config has hostName="pi", so declare
      # it here. The value already lives in tests/secrets/test.yaml.
      sops.secrets.restic-password = { };

      # Caddy test overrides — skip ACME, skip cloudflare plugin.
      services.caddy.package = lib.mkForce pkgs.caddy;
      services.caddy.globalConfig = lib.mkForce ''
        # `local_certs` makes Caddy issue self-signed certs from its
        # internal CA for ALL sites — no external ACME contact, no
        # cloudflare token required. Standard pattern for test envs.
        local_certs
      '';

      # caddy.nix hardcodes sopsFile = ../../secrets/apps.yaml for the
      # cloudflare-acme-token. Test secrets live elsewhere — point at
      # tests/secrets/test.yaml. The token isn't actually used by the
      # local_certs path; it just needs to decrypt cleanly so the
      # template + secret activation steps complete.
      sops.secrets.cloudflare-acme-token.sopsFile = lib.mkForce ./secrets/test.yaml;

      # Test framework's nixpkgs.config differs from base.nix's;
      # force ours to match the test framework to avoid the
      # allowUnfree conflict.
      nixpkgs.config = lib.mkForce {
        allowAliases = true;
        allowBroken = false;
        allowUnfree = false;
      };

      # Smaller closure for faster test boot.
      documentation.enable = lib.mkForce false;

      # `dig` for the DNS-resolution assertions + `curl` (for OIDC
      # flow subtests; the systemd path's curl is also fine but the
      # explicit dep makes the test's intent obvious).
      environment.systemPackages = [
        pkgs.bind.dnsutils
        pkgs.curl
        pkgs.jq
      ];
    };

  testScript = ''
    start_all()
    pi.wait_for_unit("multi-user.target")

    with subtest("blocky.service reaches active state"):
        pi.wait_for_unit("blocky.service")
        pi.wait_for_open_port(53)

    with subtest("lanRoutes → blocky customDNS auto-generation works"):
        # smoke.test.lan and another.test.lan are both declared in
        # nori.lanRoutes; the networking module's customDNS generator
        # should map each to nori.lanIp (10.0.0.20) automatically.
        smoke = pi.succeed("dig +short +time=2 +tries=1 smoke.test.lan @127.0.0.1")
        assert "10.0.0.20" in smoke, f"smoke.test.lan: expected 10.0.0.20, got: {smoke!r}"

        another = pi.succeed("dig +short +time=2 +tries=1 another.test.lan @127.0.0.1")
        assert "10.0.0.20" in another, f"another.test.lan: expected 10.0.0.20, got: {another!r}"

    with subtest("gatus.timer activates"):
        # gatus.service has wantedBy=[] in the homelab module — it's
        # fired by gatus.timer at OnBootSec=60s instead (so cross-host
        # rebuilds don't trigger probe-flapping). Wait for the timer
        # to be active; the service itself starts on the timer's
        # schedule.
        pi.wait_for_unit("gatus.timer")

    with subtest("heartbeat.timer activates"):
        # heartbeat.service is a oneshot — the timer wants to fire it
        # every 60s. We don't care if the curl succeeds (the URL is
        # a stub comment, not a real hc.io endpoint); we DO care that
        # the timer activates without systemd refusing to load it.
        pi.wait_for_unit("heartbeat.timer")

    with subtest("caddy.service starts + binds :443"):
        # caddy uses local_certs (internal CA) — no real ACME contact.
        # Validates: caddy module evals, the auto-generated vhost
        # config (from nori.lanRoutes) is syntactically valid, caddy
        # binds to :443. Doesn't try to proxy requests through to
        # synthetic backends — upstreams aren't reachable in this
        # single-node test.
        pi.wait_for_unit("caddy.service")
        pi.wait_for_open_port(443)

    with subtest("authelia-main.service starts + binds :9091"):
        # The real load-bearing Phase 6 check. Authelia parses every
        # decrypted secret at startup — argon2id user hash, RSA-PSS
        # issuer key, storage-encryption-key length, jwt/session/
        # hmac secrets. If any one is malformed, authelia-main exits
        # non-zero within seconds. Reaching active + binding 9091
        # proves the entire sops → file → authelia parse pipeline is
        # composed correctly.
        pi.wait_for_unit("authelia-main.service")
        pi.wait_for_open_port(9091)

        # Health probe — authelia exposes /api/health unauthenticated.
        # `ok` confirms it's not just listening but actually serving.
        health = pi.succeed("curl -fsS http://127.0.0.1:9091/api/health")
        assert "OK" in health or "ok" in health, f"unhealthy: {health!r}"

    with subtest("OIDC discovery: /.well-known/openid-configuration via caddy"):
        # Caddy must route `auth.test.lan` to authelia (127.0.0.1:9091).
        # --resolve overrides DNS (the VM's blocky resolves to
        # 10.0.0.20 — the nori.lanIp synthetic addr — which isn't
        # bound on this single-node test; localhost is). -k skips
        # cert verification because caddy uses internal CA.
        meta = pi.succeed(
            "curl -fsS -k --resolve auth.test.lan:443:127.0.0.1 "
            "https://auth.test.lan/.well-known/openid-configuration"
        )
        # Real OIDC discovery doc must include the issuer we configured.
        # If caddy were proxying to the wrong place, or authelia hadn't
        # loaded the RSA key, this would 500 or 404.
        assert '"issuer":"https://auth.test.lan"' in meta, (
            f"OIDC discovery doc missing expected issuer: {meta!r}"
        )

    with subtest("authelia first-factor: real argon2id hash authenticates"):
        # Authelia's API endpoint for username+password auth. The
        # password matches the argon2id hash generated by
        # scripts/regen-test-secrets.sh and committed into
        # tests/secrets/test.yaml's `authelia-users-database` key.
        # Authentication succeeding here proves:
        #   • sops decrypted the users database file
        #   • authelia parsed the YAML inside it
        #   • authelia's argon2id verifier accepts our generated hash
        #   • the session cookie is issued + roundtrips correctly
        # The body shape comes from authelia's REST API contract.
        login = pi.succeed(
            "curl -fsS -k -c /tmp/cookies.txt -b /tmp/cookies.txt "
            "--resolve auth.test.lan:443:127.0.0.1 "
            "-X POST -H 'Content-Type: application/json' "
            '-d \'{"username":"nori","password":"test-password-do-not-use-in-prod","keepMeLoggedIn":false,"targetURL":"https://auth.test.lan/"}\' '
            "https://auth.test.lan/api/firstfactor"
        )
        # Authelia returns {"status":"OK","data":{...}} on success.
        assert '"status":"OK"' in login, f"login failed: {login!r}"

        # State check with the issued cookie — confirms authentication
        # persisted across the request boundary.
        state = pi.succeed(
            "curl -fsS -k -b /tmp/cookies.txt "
            "--resolve auth.test.lan:443:127.0.0.1 "
            "https://auth.test.lan/api/state"
        )
        # `authentication_level >= 1` means the session is authenticated.
        # Parse the JSON properly — substring matching is too fragile.
        level = pi.succeed(
            f"echo {repr(state)} | jq -r '.data.authentication_level'"
        ).strip()
        assert int(level) >= 1, (
            f"session not authenticated post-login: level={level}, state={state!r}"
        )

    with subtest("forwardAuth: gated route rejects unauthed, accepts cookie, exempts /api/*"):
        # Composition under test (the OTHER auth pattern vs OIDC):
        # request → caddy → forward_auth /api/verify → 401 unauth OR
        # 200 with backend bytes. Exemption: /api/* bypasses the auth
        # check entirely (covers app-to-app API key flows).
        gated_backend = pi.wait_for_unit("gated-backend.service")
        pi.wait_for_open_port(7878)

        # Fresh cookie jar — the OIDC subtest above left a session
        # cookie. Reuse it; *.test.lan sessions span both routes.
        # Unauth flow: drop the cookie, expect 401 from authelia's
        # verify (caddy returns it as the proxy response).
        unauth_status = pi.succeed(
            "curl -s -o /dev/null -w '%{http_code}' "
            "-k --resolve gated.test.lan:443:127.0.0.1 "
            "https://gated.test.lan/"
        ).strip()
        # Authelia returns 401 on /api/verify failure; caddy
        # may surface that, or rewrite to a 302 redirect to the
        # portal. Either signals "not authorized through".
        assert unauth_status in ("401", "302"), (
            f"unauthed request not rejected: status={unauth_status!r}"
        )

        # Authed flow: the cookie jar from the prior login subtest
        # carries the session. forward_auth /api/verify returns 200,
        # caddy proxies through to the backend.
        authed = pi.succeed(
            "curl -fsS -k -b /tmp/cookies.txt "
            "--resolve gated.test.lan:443:127.0.0.1 "
            "https://gated.test.lan/"
        ).strip()
        assert authed == "gated-backend-ok", (
            f"authed gated request didn't reach backend: {authed!r}"
        )

        # Exempt path: /api/* bypasses forward-auth entirely. Hit
        # without any cookie, expect the backend's marker for the
        # /api branch.
        exempt = pi.succeed(
            "curl -fsS -k "
            "--resolve gated.test.lan:443:127.0.0.1 "
            "https://gated.test.lan/api/v3/whatever"
        ).strip()
        assert exempt == "api-exempt-ok", (
            f"exempt /api/* path didn't bypass auth: {exempt!r}"
        )

    with subtest("OnFailure → notify@ → ntfy POST"):
        # Composition under test:
        #   test-failing-unit → OnFailure → notify@test-failing-unit.service
        #     → script sleeps recoveryWindowSeconds (3 in test, 120 in prod)
        #     → re-checks if recovered
        #     → curls baseUrl + "/" + channel
        #
        # Stub receiver captures POSTs at /var/lib/test-ntfy/messages.
        # We assert the channel path and a body fragment that comes from
        # the journal tail (the failing unit name appears in the body).
        pi.wait_for_unit("test-ntfy-receiver.service")

        # Sanity: the receiver hasn't logged anything yet.
        pi.succeed("test ! -s /var/lib/test-ntfy/messages || ! grep -q . /var/lib/test-ntfy/messages")

        # Trip the bait. The unit exits non-zero so `systemctl start`
        # itself returns non-zero — `|| true` swallows that since the
        # FAILURE is what we want, not what we want to fail the test on.
        pi.succeed("systemctl start test-failing-unit.service || true")

        # The unit failed → notify@test-failing-unit.service kicked off
        # via OnFailure → it sleeps 3s → POSTs to the stub. Wait for the
        # receiver to register the message.
        pi.wait_until_succeeds(
            "test -s /var/lib/test-ntfy/messages && "
            "grep -q 'test-failing-unit' /var/lib/test-ntfy/messages",
            timeout=30,
        )

        captured = pi.succeed("cat /var/lib/test-ntfy/messages")

        # URL path must be /<channel> from sops; the test channel
        # value is "test-channel" (see scripts/regen-test-secrets.sh).
        assert "PATH=/test-channel" in captured, (
            f"expected POST to /test-channel, got: {captured!r}"
        )
        # Title header should name the failing unit; body should
        # reference the failed state for the test-failing-unit.
        assert "test-failing-unit" in captured, (
            f"alert body missing failing-unit name: {captured!r}"
        )
        # Priority header survives the curl invocation.
        assert "HDR Priority: urgent" in captured, (
            f"missing Priority header: {captured!r}"
        )
  '';
}
