{ inputs, pkgs, ... }:
let
  # SUPER+H invokes this — list of binds piped into fuzzel's --dmenu mode
  # for a search-as-you-type cheatsheet. Update the heredoc when binds
  # change; nothing parses hyprland.conf to keep this in sync (would be
  # brittle with multi-arg dispatchers and quote-escaped exec strings).
  cheatsheet = pkgs.writeShellScriptBin "hypr-cheatsheet" ''
    ${pkgs.fuzzel}/bin/fuzzel --dmenu --prompt "binds: " --width 60 --lines 18 >/dev/null <<'EOF'
    SUPER + RETURN       ghostty (terminal)
    SUPER + SPACE        fuzzel (launcher)
    SUPER + B            zen (browser)
    SUPER + H            this cheatsheet
    SUPER + L            lock screen
    SUPER + Q            close window
    SUPER + V            toggle floating
    SUPER + F            fullscreen
    SUPER + SHIFT + E    exit Hyprland
    SUPER + arrows       focus left/down/up/right
    SUPER + J / K        focus down/up (vim-style)
    SUPER + 1..9         switch to workspace
    SUPER + SHIFT + 1..9 move window to workspace
    SUPER + drag-LMB     move window
    SUPER + drag-RMB     resize window
    PRINT                screenshot region → clipboard
    EOF
  '';
in
{
  # home-manager as a NixOS module (per DESIGN.md L355-358) — config flows
  # from this Nix attrset into ~/.config/hypr/hyprland.conf etc. at
  # activation time.
  imports = [ inputs.home-manager.nixosModules.home-manager ];

  home-manager = {
    useGlobalPkgs = true; # use system nixpkgs, don't fork a per-user one
    useUserPackages = true; # install user pkgs to /etc/profiles/per-user
    extraSpecialArgs = { inherit inputs; };

    # Move pre-existing files aside instead of failing the activation when
    # home-manager wants to symlink in a managed copy. Bit us once already:
    # Hyprland writes an autogenerated `~/.config/hypr/hyprland.conf` on
    # first launch if no config exists; if the user logs in before
    # home-manager has activated, the file lands first and HM refuses to
    # clobber. Backed-up file lands at <path>.hm-backup.
    backupFileExtension = "hm-backup";

    users.nori = {
      home.stateVersion = "25.11"; # match host's system.stateVersion
      programs.home-manager.enable = true;

      # Cursor — bibata-modern-classic at 24px reads well on the 34" 1440p
      # panel (~6.5mm physical). gtk + x11 + hyprcursor.enable = false
      # because bibata doesn't ship the hyprcursor format yet; XCURSOR is
      # the universal fallback Hyprland honors via the `env` directives
      # below. Swap theme by changing `name` + `package`; size by `size`.
      home.pointerCursor = {
        package = pkgs.bibata-cursors;
        name = "Bibata-Modern-Classic";
        size = 24;
        gtk.enable = true;
        x11.enable = true;
      };

      wayland.windowManager.hyprland = {
        enable = true;

        # Use the system Hyprland (programs.hyprland.enable = true above).
        # Without this home-manager would also install a user-scope copy
        # and the two could drift across rebuilds.
        package = null;
        portalPackage = null;

        settings = {
          # Samsung S34J552 — 34" ultrawide, native 3440x1440 @ 75Hz on DP-3.
          # Position 0x0, scale 1.0 (panel is large enough that 1440p reads
          # well at 1:1; bump to 1.25 if text feels small).
          monitor = [ "DP-3,3440x1440@75,0x0,1" ];

          # Norwegian keymap to mirror modules/common/base.nix (console.keyMap).
          input = {
            kb_layout = "no";
            follow_mouse = 1;
            sensitivity = 0;
          };

          general = {
            gaps_in = 4;
            gaps_out = 8;
            border_size = 2;
            layout = "dwindle";
          };

          decoration = {
            rounding = 4;
          };

          dwindle = {
            pseudotile = true;
            preserve_split = true;
          };

          # Cursor theme propagation — Hyprland exports these to children
          # at startup. Matches home.pointerCursor above.
          env = [
            "XCURSOR_THEME,Bibata-Modern-Classic"
            "XCURSOR_SIZE,24"
          ];

          # Mod key — SUPER (Windows / Cmd-equivalent).
          "$mod" = "SUPER";

          bind = [
            # Apps
            "$mod, RETURN, exec, ghostty"
            "$mod, SPACE,  exec, fuzzel"
            "$mod, B,      exec, zen"

            # Help / session
            "$mod, H, exec, ${cheatsheet}/bin/hypr-cheatsheet"
            "$mod, L, exec, loginctl lock-session"

            # Window
            "$mod, Q, killactive,"
            "$mod SHIFT, E, exit,"
            "$mod, V, togglefloating,"
            "$mod, F, fullscreen,"

            # Focus — H and L claimed by cheatsheet/lock above; J/K kept
            # for vim-style down/up; arrows cover all four directions.
            "$mod, j, movefocus, d"
            "$mod, k, movefocus, u"
            "$mod, left,  movefocus, l"
            "$mod, down,  movefocus, d"
            "$mod, up,    movefocus, u"
            "$mod, right, movefocus, r"

            # Workspaces 1-9
            "$mod, 1, workspace, 1"
            "$mod, 2, workspace, 2"
            "$mod, 3, workspace, 3"
            "$mod, 4, workspace, 4"
            "$mod, 5, workspace, 5"
            "$mod, 6, workspace, 6"
            "$mod, 7, workspace, 7"
            "$mod, 8, workspace, 8"
            "$mod, 9, workspace, 9"

            "$mod SHIFT, 1, movetoworkspace, 1"
            "$mod SHIFT, 2, movetoworkspace, 2"
            "$mod SHIFT, 3, movetoworkspace, 3"
            "$mod SHIFT, 4, movetoworkspace, 4"
            "$mod SHIFT, 5, movetoworkspace, 5"
            "$mod SHIFT, 6, movetoworkspace, 6"
            "$mod SHIFT, 7, movetoworkspace, 7"
            "$mod SHIFT, 8, movetoworkspace, 8"
            "$mod SHIFT, 9, movetoworkspace, 9"

            # Screenshot region → clipboard (shell-script-y; replace later
            # with a wrapper if it grows beyond one line).
            ", PRINT, exec, grim -g \"$(slurp)\" - | wl-copy -t image/png"
          ];

          bindm = [
            # Mouse drag move/resize
            "$mod, mouse:272, movewindow"
            "$mod, mouse:273, resizewindow"
          ];

          # Autostart — polkit agent for elevation prompts.
          # Wallpaper / status bar / notification daemon are deferred to
          # follow-up commits (waybar, mako, hyprpaper config).
          exec-once = [
            "systemctl --user start hyprpolkitagent"
          ];
        };
      };
    };
  };
}
