{
  config,
  lib,
  inputs,
  ...
}:

{
  /**
    workstation is a server + a desktop. Each `modules/<concern>`
    import is one role this machine plays; the host is the sum of
    its concerns plus its physical hardware.
  */
  imports = [
    inputs.disko.nixosModules.disko
    inputs.home-manager.nixosModules.home-manager

    ../base # base + users + sops + tailscale + lib options
    ../../services # every server module (HTTP, *arr, backup, …)
    ../desktop # Hyprland + greetd + audio + bars + apps + gaming

    ./hardware.nix
    ./disko.nix
    ./disko-media.nix
    ./disko-mp510.nix
  ];

  /*
    home-manager-as-NixOS-module wrapper. Activates the user's home
    config (./home.nix — pure home-manager module shape) as part of
    nixos-rebuild. The same shape lives in modules/machines/pi/default.nix;
    extract a shared snippet at the third instance.
  */
  home-manager = {
    useGlobalPkgs = true; # use system nixpkgs, don't fork a per-user one
    useUserPackages = true; # install user pkgs to /etc/profiles/per-user
    extraSpecialArgs = { inherit inputs; };
    /*
      Move pre-existing files aside instead of failing the activation
      when home-manager wants to symlink in a managed copy. Bit us once
      already: Hyprland writes an autogenerated ~/.config/hypr/
      hyprland.conf on first launch if no config exists; if the user
      logs in before home-manager has activated, the file lands first
      and HM refuses to clobber. Backed-up file lands at <path>.hm-backup.
    */
    backupFileExtension = "hm-backup";
    users.nori.imports = [ ./home.nix ];
  };

  # networking.hostName injected from the registry key in flake.nix.
  networking.useDHCP = lib.mkDefault true;

  /*
    Add the operator user to the `media` group so shell access + any
    service running as `nori` (Syncthing's binds, e.g.) can write to
    /mnt/media/{downloads,library} which are owned root:media 02775
    by arr/shared.nix tmpfiles. The group itself is defined in
    arr/shared.nix — workstation-only, hence the workstation-host-
    scope here rather than common/users.nix (which Pi also reads).
  */
  users.users.nori.extraGroups = [ "media" ];

  /*
    Service-placement registry. Each modules/services/*.nix that wraps
    itself in `mkIf config.nori.services.<name>.enabled` gets explicitly
    enabled here. Workstation is the workhorse — it runs the GPU /
    compute / acquisition layer (arr stack, qBittorrent, Jellyfin,
    Ollama, Open WebUI, Stremio, Syncthing, observability agents).
    Family-tier serving (Immich, Navidrome, Calibre-web, Komga,
    Vaultwarden, etc.) lives on aurora; the HTTP entry plane (Caddy,
    Authelia, Blocky-authoritative) lives on pi. Moves between hosts:
    flip `enable` on the destination, unset here.
  */
  nori.services = {
    # arr stack + qBit (media-server)
    bazarr.enable = true;
    jellyseerr.enable = true;
    lidarr.enable = true;
    prowlarr.enable = true;
    qbittorrent.enable = true;
    radarr.enable = true;
    recyclarr.enable = true;
    sonarr.enable = true;
    # Family-tier + network appliance + media-reader
    authelia.enable = false; # pi entry plane post-P12; pi's authelia is the SSO instance
    blocky.enable = true;
    caddy.enable = false; # pi entry plane post-P12; pi's caddy fronts every route via runsOn
    calibre-web.enable = false;
    filmder.enable = false;
    glance.enable = false;
    heim.enable = false;
    immich.enable = false;
    jellyfin.enable = true;
    komga.enable = false;
    miniflux.enable = false;
    navidrome.enable = false;
    open-webui.enable = true;
    radicale.enable = false;
    samba.enable = true;
    stremio.enable = true;
    syncthing.enable = true;
    vaultwarden.enable = false;
    # GPU-bound
    ollama.enable = true;
    # Observability + alerting
    beszel-agent.enable = true;
    disk-alert.enable = true;
    gatus.enable = true;
    grafana.enable = false;
    node-exporter.enable = true;
    nvidia-gpu-exporter.enable = true;
    ntfy-notify.enable = true;
    # Backup
    btrbk-replica-target.enable = true; # P15 — receives btrfs send from aurora into MP510
  };

  # FLAC→Opus library mirror (timer). Keeps ${library}/music-opus current from
  # the lossless library so Syncthing can push the compressed tree to the phone.
  # Standalone — independent of the (undeployed) tonic daemon. See ADR/plan:
  # the operator's real workflow is SpotiFLAC-Mobile → Syncthing → mirror → phone.
  nori.musicMirror.enable = true;

  # FLAC ingest (timer, sibling to music-mirror). The phone pushes new lossless
  # FLAC into a transient Syncthing staging dir; this MOVEs complete, stable
  # files into the master library and deletes the staging copy (a separate
  # Syncthing folder propagates that delete back to the phone, freeing its FLAC).
  # Staging is deliberately OUTSIDE ${library}: no backup intent, and the phone
  # can never reach the master. See docs/runbooks/music-opus-mirror.md.
  nori.musicIngest = {
    enable = true;
    stagingPath = "/mnt/media/staging/music-flac";
  };

  # Pre-create the staging tree. /mnt/media is root:root, so Syncthing (runs as
  # nori, in `media`) can't mkdir under it. root:media 2775 (setgid) lets both
  # Syncthing receive into it and the music-ingest user delete from it; new
  # files inherit the media group.
  systemd.tmpfiles.rules = [
    "d /mnt/media/staging            0755 root root  - -"
    "d /mnt/media/staging/music-flac 2775 root media - -"
  ];

  # Syncthing's sandbox (nori.harden) binds only library + downloads by default,
  # so the new staging dir is invisible inside the service namespace ("folder
  # path missing"). Bind it RW so Syncthing can receive the phone's FLAC into it
  # and propagate the ingest's deletes back. music-ingest reaches it via its own
  # harden binds.
  nori.harden.syncthing.binds = [ "/mnt/media/staging/music-flac" ];

  # Syncthing creates received dirs with its process umask; the default 0022
  # leaves them group-unwritable (drwxr-sr-x), so the media-group music-ingest
  # user can't unlink files from Syncthing-created staging subdirs (unlink needs
  # WRITE on the parent dir, not the file). 0002 → group-writable trees, matching
  # the media-group collaboration model (the library is already root:media 02775).
  systemd.services.syncthing.serviceConfig.UMask = "0002";

  /*
    Defensive cap on user@1000.service. Calibrated against the
    2026-06-08 global-OOM event: a leak inside the user session climbed
    to 26.2 GiB RSS + 21.5 GiB swap peak in 3h, exhausted total memory
    (32 GiB RAM + 16 GiB zram + 8 GiB disk swap), and the kernel OOM
    killer fired with CONSTRAINT_NONE — killing lua-language-server
    inside the Hyprland session and cascading user@1000 to deactivate,
    taking down the entire desktop.

    MemoryHigh = soft cap, throttles via swap pressure when reached.
    MemoryMax  = hard cap, OOM-kills inside the unit instead of system-
                 wide. With the cap, a runaway desktop kills itself and
                 system services (sshd, caddy, blocky, tailscaled) stay
                 alive — recoverable from a TTY or remote SSH.

    Numbers leave ≥4 GiB physical + 8 GiB swap headroom for kernel,
    system slice, and a brief grace for terminating processes. Track
    the actual session footprint in process-exporter (ROADMAP #45) and
    tighten if normal heavy use stays well under.
  */
  systemd.services."user@".serviceConfig = {
    MemoryHigh = "24G";
    MemoryMax = "28G";
  };

  /*
    Station-side Gatus probes for non-HTTP services. HTTP services
    behind Caddy are auto-probed via nori.lanRoutes.<n>.monitor.

    Mutual observability: station probes Pi's Blocky + SSH via tailnet
    IP; pi has matching probes for station (modules/machines/pi/default.nix).
    Each host's Gatus alerts via ntfy.sh directly (no local-ntfy
    dependency), so one host's outage gets caught by the other.
  */
  nori.gatusProbes = {
    blocky-dns.url = "tcp://127.0.0.1:53";
    samba-smb.url = "tcp://127.0.0.1:445";
    pi-blocky-dns.url = "tcp://${config.nori.hosts.pi.tailnetIp}:53";
    pi-ssh.url = "tcp://${config.nori.hosts.pi.tailnetIp}:22";
    aurora-ssh.url = "tcp://${config.nori.hosts.aurora.tailnetIp}:22";
    aurora-samba.url = "tcp://${config.nori.hosts.aurora.tailnetIp}:445";
  };
}
