---
extends: default

ignore: |
  .devenv/

rules:
  braces:
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
    ignore: |
      tests/vm/user-data.yml
  comments-indentation: false
  document-start:
    ignore: |
      tests/vm/user-data.yml
  line-length:
    max: 120
    level: warning
  octal-values:
    forbid-explicit-octal: true
    forbid-implicit-octal: true
  truthy:
    allowed-values:
      - "true"
      - "false"
