[project]
name = "homelab-pi"
revision = "1.0"

[providers]
keyring = "keyring://"
env = "env://"

[profiles.production.defaults]
providers = ["keyring", "env"]

[profiles.production]
PIHOLE_WEB_PASSWORD = { description = "Pi-hole production administrator password", required = true }
TAILSCALE_AUTH_KEY = { description = "Ephemeral Tailscale enrollment key", required = false }
