---
- name: Reload systemd after Beszel agent changes
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart Beszel agent
  ansible.builtin.systemd_service:
    name: beszel-agent.service
    state: restarted
